version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    command: yarn dev
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypass
      DB_DATABASE: mydb
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
